on: [push, pull_request]

name: CI

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      rust_version: ${{ steps.read_toolchain.outputs.rust_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Read rust version"
        id: read_toolchain
        run: echo "rust_version=$(cat rust-version)" >> $GITHUB_OUTPUT

  build-test:
    needs: prepare
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        rust:
          - version: ${{ needs.prepare.outputs.rust_version }}
            clippy: true
          - version: 1.63.0 # Overall MSRV
        features:
          - --no-default-features --features miniscript/no-std,bdk_chain/hashbrown
          - --all-features
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust.version }}
            override: true
            profile: minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Build + Test
        env:
          MATRIX_RUST_VERSION: ${{ matrix.rust.version }}
        run: |
          cargo build --locked --workspace --exclude 'example_*' ${{ matrix.features }}
          cargo test --locked --workspace --exclude 'example_*' ${{ matrix.features }}

  check-no-std:
    needs: prepare
    name: Check no_std
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ needs.prepare.outputs.rust_version }}
          override: true
          profile: minimal
          # target: "thumbv6m-none-eabi"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Check bdk wallet
        working-directory: ./wallet
        # TODO "--target thumbv6m-none-eabi" should work but currently does not
        run: cargo check --locked --no-default-features --features miniscript/no-std,bdk_chain/hashbrown

  check-wasm:
    needs: prepare
    name: Check WASM
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    env:
      CC: clang-14
      CFLAGS: -I/usr/include
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install WASM C toolchain
        timeout-minutes: 5
        run: |
          sudo apt-get -o Acquire::Retries=3 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update
          sudo apt-get -o Acquire::Retries=3 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 install -y libclang-common-14-dev clang-14 libc6-dev-i386
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ needs.prepare.outputs.rust_version }}
            override: true
            profile: minimal
            target: "wasm32-unknown-unknown"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Check bdk wallet
        working-directory: ./wallet
        run: cargo check --locked --target wasm32-unknown-unknown --no-default-features --features miniscript/no-std,bdk_chain/hashbrown

  fmt:
    needs: prepare
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ needs.prepare.outputs.rust_version }}
            override: true
            profile: minimal
            components: rustfmt
      - name: Check fmt
        run: cargo fmt --all -- --config format_code_in_doc_comments=true --check

  clippy_check:
    needs: prepare
    name: Rust clippy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ needs.prepare.outputs.rust_version }}
            components: clippy
            override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Clippy Results
          args: --locked --all-features --all-targets -- -D warnings

  build-examples:
    needs: prepare
    name: Build & Test Examples
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        example-dir:
          - example_wallet_electrum
          - example_wallet_esplora_async
          - example_wallet_esplora_blocking
          - example_wallet_rpc
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ needs.prepare.outputs.rust_version }}
          override: true
          profile: minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Build
        working-directory: examples/${{ matrix.example-dir }}
        run: cargo build --locked
